# Step 1: Build Vite app
FROM node:18 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy rest and .env.production generated by Cloud Build
COPY . .

# Build using .env.production
RUN npm run build

# Step 2: Serve the app
FROM node:18-slim
WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist ./dist

EXPOSE 8080

CMD ["serve", "-s", "dist", "-l", "8080"]
